title: SH Investment
tagline: Research & Contents
description: "SH Investment Research & Contents"

url: "https://johnjung727-dot.github.io"
baseurl: "/SHinvestment.github.io"

avatar: "/assets/profile.png"

theme: jekyll-theme-chirpy
lang: ko
